#+title: Accelerating CUP reconstruction using NESTA optimization algorithm
#+author: Liren Zhu

#+begin_abstract
This is a summary of theoretical and algorithmic results that are related with
using the NESTA algorithm in CUP reconstruction. The motivation of using NESTA
is to mitigate the major computational cost on the TV denoising proxy problem
that needs to be solved in every iteration of the TwIST and FISTA optimizers. I
have included the framework of NESTA, detailed factorization of using NESTA with
different CUP implementations, and derivation of the major steps in this note.
This document will, hopefully, help readers, including myself, to better
understand the implementation of this method.
#+end_abstract

* Introduction
  Currently, Compressed Ultrafast Photography (CUP) relies on a family of
  Iterative Shrinkage/Thresholding Algorithms (ISTA), including the Two-step
  Iterative Shrinkage/Thresholding (TwIST) algorithm and the Fast Iterative
  Shrinkage/Thresholding Algorithm (FISTA), to reconstruct the final datacube of
  the dynamic scene. While these methods produce excellent results, their needs
  of solving the Total Variation (TV) denoising proxy problem in every iteration
  are shown to make up most of the computation time, as well as require the user
  to pick non-intuitive parameters for the proxy problem.

  The NESTA optimizer, on the other hand, requires only one call to the
  differentiation operator and its adjoint each during on iteration, in order to
  realize l2 constrained TV minimization. Considering that CUP's observation
  operator and its adjoint (of all CUP implementations) are relatively cheap to
  perform, an optimizer that minimizes the computation time on TV is an ideal
  choice for CUP. In addition, instead of solving the TV-regularized l2 error
  minimization problem
  #+name: eq1
  \begin{equation}
  \min_x \frac{1}{2} \lVert b - Ax \rVert_2^2 + \lambda \lVert x
  \rVert_{\text{TV}}
  \end{equation}
  NESTA solves the following, more direct problem
  #+name: eq2
  \begin{equation}
  \min_x \lVert x \rVert_{\text{TV}} \quad \text{s.t.} \lVert b - Ax \rVert_2
  \le \epsilon
  \end{equation}
  While Eq. ([[eq1]]) has a rather arbitrary parameter $\lambda$, Eq. ([[eq2]]) requires
  a parameter $\epsilon$, which is closely related with the upper bound of the
  measurement noises. However, it is worth noticing that theoretical analyses
  have shown that Eq. ([[eq1]]) and ([[eq2]]) are equivalent when $\lambda$ and
  $\epsilon$ follow a certain relation and the true optimal points were reached
  in both problems.
